name: "Cronjob"
on:
schedule:
- cron: '15 * * * *'

jobs:
    update-weather:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Generate README
              uses: huantt/weather-forecast@v1.0.5
              with:
              city: HaNoi
              days: 7
              weather-api-key: f5492d7dd42c4829be424812231409
              template-file: 'README.md'
              out-file: 'README.md'
            - name: Commit
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "update weather"
                git push origin main
